export const projectsTable = [
  {
    id: "1",
    url: "https://www.xfoliado.com",
    title: "Test",
    type: "Design / Marketing",
    icon: "https://cdn.vuetifyjs.com/images/backgrounds/vbanner.jpg",
    year: 2020,
    live: true,
    desc: "Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description.",
    technologies: ["React", "JS", "PHP"],
    participation: ["Frontend", "Backend", "Database", "Server"],
  },
  {
    id: "2",
    url: "https://www.xfoliado.com",
    title: "Test",
    type: "Design / Marketing",
    icon: "https://cdn.vuetifyjs.com/images/backgrounds/vbanner.jpg",
    year: 2020,
    live: true,
    desc: "Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description.",
    technologies: ["React", "JS", "PHP"],
    participation: ["Frontend", "Backend", "Database", "Server"],
  },
  {
    id: "3",
    url: "https://www.xfoliado.com",
    title: "Test",
    type: "Design / Marketing",
    icon: "https://cdn.vuetifyjs.com/images/backgrounds/vbanner.jpg",
    year: 2020,
    live: true,
    desc: "Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description.",
    technologies: ["React", "JS", "PHP"],
    participation: ["Frontend", "Backend", "Database", "Server"],
  },
  {
    id: "4",
    url: "https://www.xfoliado.com",
    title: "Test",
    type: "Design / Marketing",
    icon: "https://cdn.vuetifyjs.com/images/backgrounds/vbanner.jpg",
    year: 2020,
    live: false,
    desc: "Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description.",
    technologies: ["React", "JS", "PHP"],
    participation: ["Frontend", "Backend", "Database", "Server"],
  },
  {
    id: "5",
    url: "https://www.xfoliado.com",
    title: "Test",
    type: "ECommerce",
    icon: "https://cdn.vuetifyjs.com/images/backgrounds/vbanner.jpg",
    year: 2020,
    live: false,
    desc: "Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description.",
    technologies: ["React", "JS", "PHP"],
    participation: ["Frontend", "Backend", "Database", "Server"],
  },
  {
    id: "6",
    url: "https://www.xfoliado.com",
    title: "Test",
    type: "ECommerce",
    icon: "https://cdn.vuetifyjs.com/images/backgrounds/vbanner.jpg",
    year: 2020,
    live: false,
    desc: "Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description Test Description.",
    technologies: ["React", "JS", "PHP"],
    participation: ["Frontend", "Backend", "Database", "Server"],
  },
];

export default defineEventHandler(async () => projectsTable);
