export const db = {
  author: {
    role: "Full-Stack Developper",
    desc: "I am a full-stack developper originating from the Dominican Republic seeking to be one of the essentials piece in any web development project",
    name: process.env.NUXT_NAME,
    year: process.env.NUXT_YEAR,
    number: process.env.NUXT_NUMBER,
    email: process.env.NUXT_EMAIL,
    country: process.env.NUXT_COUNTRY,
    language: process.env.NUXT_LANGUAGE,
    picture: process.env.NUXT_PICTURE,
    available: "Yes",
  },
  skills: [
    {
      icon: "https://img.icons8.com/?size=100&id=25Sjy8fKExYA&format=png&color=000000",
      name: "ReactJS",
      expertise: 90,
    },
    {
      icon: "https://img.icons8.com/?size=100&id=45490&format=png&color=000000",
      name: "C#",
      expertise: 80,
    },
    {
      icon: "https://img.icons8.com/?size=100&id=BUnExfsRs3CW&format=png&color=000000",
      name: "VueJS",
      expertise: 70,
    },
    {
      icon: "https://img.icons8.com/?size=100&id=V6HShIzw21x7&format=png&color=000000",
      name: "Javascript",
      expertise: 100,
    },
    {
      icon: "https://img.icons8.com/?size=100&id=sH0rW2TvYdr9&format=png&color=000000",
      name: "Supabase",
      expertise: 80,
    },
    {
      icon: "https://img.icons8.com/?size=100&id=74402&format=png&color=000000",
      name: "MongoDB",
      expertise: 70,
    },
    {
      icon: "https://img.icons8.com/?size=100&id=wU62u24brJ44&format=png&color=000000",
      name: "Amazon Web Services",
      expertise: 60,
    },
    {
      icon: "https://img.icons8.com/?size=100&id=13682&format=png&color=000000",
      name: "Cloudflare",
      expertise: 40,
    },
    {
      icon: "https://img.icons8.com/?size=100&id=22813&format=png&color=000000",
      name: "Docker",
      expertise: 80,
    },
    {
      icon: "https://img.icons8.com/?size=100&id=38561&format=png&color=000000",
      name: "PostgresSQL",
      expertise: 60,
    },
    {
      icon: "https://img.icons8.com/?size=100&id=UGYn5TapNioV&format=png&color=000000",
      name: "PHP",
      expertise: 40,
    },
    {
      icon: "https://img.icons8.com/?size=100&id=13679&format=png&color=000000",
      name: "Java",
      expertise: 50,
    },
    {
      icon: "https://img.icons8.com/?size=100&id=20906&format=png&color=000000",
      name: "Git",
      expertise: 80,
    },
    {
      icon: "https://img.icons8.com/?size=100&id=39292&format=png&color=000000",
      name: "Jenkins",
      expertise: 70,
    },
  ],
  experiences: [
    {
      name: "Eleganteus Marketplace S.R.L",
      icon: "https://img.icons8.com/?size=100&id=EPg0SfDrfTSe&format=png&color=000000",
      years: "2024-Current",
      country: "Dominican Republic",
      type: "Fulltime",
      desc: "Worked as a Full Stack Developer responsible for designing, developing, and maintaining web applications with a strong focus on backend services built in C# and a modern React frontend. Deployed and managed frontend applications on AWS EC2, ensuring performance, scalability, and reliability. Collaborated closely with cross-functional teams to deliver secure, efficient, and user-friendly solutions.",
    },
  ],
  education: [
    {
      name: "Universidad Tecnologica de Santiago (UTESA)",
      icon: "https://pbs.twimg.com/profile_images/783336810676006914/HDJDMj4m.jpg",
      years: "2018-2024",
      country: "Dominican Republic",
      type: "University College",
      desc: "System Engineering / Computer Science",
    },
  ],
  projects: [
    {
      url: "https://www.xfoliado.com",
      title: "Test",
      type: "Design / Marketing",
      icon: "https://cdn.vuetifyjs.com/images/backgrounds/vbanner.jpg",
      year: 2020,
      live: true,
      technologies: ["React", "JS", "PHP"],
    },
    {
      url: "https://www.xfoliado.com",
      title: "Test",
      type: "Design / Marketing",
      icon: "https://cdn.vuetifyjs.com/images/backgrounds/vbanner.jpg",
      year: 2020,
      live: true,
      technologies: ["React", "JS", "PHP"],
    },
    {
      url: "https://www.xfoliado.com",
      title: "Test",
      type: "Design / Marketing",
      icon: "https://cdn.vuetifyjs.com/images/backgrounds/vbanner.jpg",
      year: 2020,
      live: true,
      technologies: ["React", "JS", "PHP"],
    },
    {
      url: "https://www.xfoliado.com",
      title: "Test",
      type: "Design / Marketing",
      icon: "https://cdn.vuetifyjs.com/images/backgrounds/vbanner.jpg",
      year: 2020,
      live: false,
      technologies: ["React", "JS", "PHP"],
    },
    {
      url: "https://www.xfoliado.com",
      title: "Test",
      type: "ECommerce",
      icon: "https://cdn.vuetifyjs.com/images/backgrounds/vbanner.jpg",
      year: 2020,
      live: false,
      technologies: ["React", "JS", "PHP"],
    },
    {
      url: "https://www.xfoliado.com",
      title: "Test",
      type: "ECommerce",
      icon: "https://cdn.vuetifyjs.com/images/backgrounds/vbanner.jpg",
      year: 2020,
      live: false,
      technologies: ["React", "JS", "PHP"],
    },
  ],
  socials: [
    {
      link: "https://github.com/bentonico98",
      name: "My Github",
      icon: "mdi-github",
    },
    {
      link: "https://www.linkedin.com/in/benjunior-dorlouis-b392b926a",
      name: "My Linkedin",
      icon: "mdi-linkedin",
    },
    {
      link: "https://www.instagram.com/papibenju",
      name: "My Instagram",
      icon: "mdi-instagram",
    },
    {
      link: "https://www.facebook.com/Benjunior.Dorlouis",
      name: "My Facebook",
      icon: "mdi-facebook",
    },
  ],
  contacts: [
    {
      value: process.env.NUXT_EMAIL,
      name: "Email",
      icon: "https://img.icons8.com/?size=100&id=53388&format=png&color=000000",
    },
    {
      value: process.env.NUXT_NUMBER,
      name: "Phone",
      icon: "https://img.icons8.com/?size=100&id=9659&format=png&color=000000",
    },
  ],
};
